### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by lukkyluke**
- Adding support for returning a specified set of properties with the expansion query parameter
- Adding support to PUT requests with only a path parameter, e.g copyDataView (that was not working properly)
- Changes to support the new(?) json formatting on credentials where there can be many client secrets.
The naming on the json object is different (lowercase / uppercase) if you download the credentials from the overview of the project versus downloading it from the oauth-credentials-tab of the project. Therefore the parser now also accepts uppercase credential properties.

### CODE REVIEW

**Comment by pitchmuc** [comment]
Thanks a lot @lukkyluke 
I will try to review this and publish a new version this week.

**Comment by lukkyluke** [comment]
> Thanks a lot @lukkyluke I will try to review this and publish a new version this week.

Sounds great @pitchmuc! :)

**Comment by pitchmuc** [comment]
Quickly running through the changes, I noticed you added more parameter capability for the different type of requests, especially using the `expansion` parameter, that I abstracted to `full`. 
That is fine, I did not need that level of granularity as most people do not care of the details but happy to provide it. 

The Auth update is most intriguing to me. 
Are you using a single file to manage multiple clients at once ? 
Curious if you set up the upper case configuration parameter on yourself to distinguish it from the base provided or if it is something coming out of an export. 

Finally, I did not notice that the auth token endpoint has been moved to v3, I checked and saw it has been done on all organizations. 
For some reasons I did not see that update or Adobe did not communicate it. 
So even if v2 is still working, moving to v3 seems a good move, thanks for that, I will update all of my wrappers to use this one now.

**Comment by lukkyluke** [comment]
Thanks for a quick response @pitchmuc (and for making a wrapper)! 
Regarding `expansion`, I thought it would be nice to limit the response object to what you actually want. But `full` is also useful in case you want the whole object :)

Regarding auth, I understand the confusion. I just realized now that the object properties are named different when downloading the whole project json, versus downloading the json from the oauth-credentials-tab (in the project details). Really annoying :) But I guess that it is nice to support both download alternatives. Maybe it would be good to address this to Adobe, so that they stick to the same formatting on both json-files.

And regarding many `client_secrets`, I don't know why that is possible (I personally just use one). It was not an array previously, in earlier versions of "the platform". But I see that you can add many client secrets to the same `client_id`.

Thumbs up on v3, forgot to mention that in the PR and the commits.

**Comment by pitchmuc** [comment]
Hello @lukkyluke
I just released the new version of cjapy, version `0.2.2.post1`, you can normally pip --upgrade it from now on. 
I modified a bit your code as you were not considering the "old" JWT auth (will be deprecated next year). 
Hence there was an error thrown for these type of connection (you expected a scope key in the config file, which is not there in JWT)

**Comment by lukkyluke** [comment]
@pitchmuc Good catch, sorry for that!

**Comment by lukkyluke** [comment]
Hi again @pitchmuc, why is version 0.2.2 yanked? 
`Reason for being yanked: fixes`

**Comment by pitchmuc** [comment]
Yes, there were some issues on Workspace and ProjectDetails elements. 
You can use the latest version: 0.2.2-2

**Comment by pitchmuc** [comment]
I can un-yank if you want but I prefer people to get to the latest version, it is normally always the one with the most fixes
.

**Comment by lukkyluke** [comment]
No problem, I just thought that the latest version was 0.2.2. I'll just go for 0.2.2-2 instead.

**Comment by lukkyluke** [comment]
Btw, I am searching for a way to update the metrics and dimensions on a dataview. Is that possible through the updateDataview-method? 

I can only find get-methods for those entities in the official [documentation](https://developer.adobe.com/cja-apis/docs/api/#tag/Dimensions-API).

**Comment by pitchmuc** [comment]
Unfortunately no :( 
I am pushing for that with the product team because it would help us so much to handle large organization setup, even the creation of new dimensions or metrics are not supported. 
I even tried to force a POST method but it will give you 404. 

You can raise an enhancement ticket from customer care, and if you talk to the BU responsible for CJA, ask for it. 
Raising awareness would help but it is not in their priority list for the moment, which is sad.

**Comment by lukkyluke** [comment]
Thanks a lot for the clarification. I will raise this issue with our Adobe representatives.

**Pull request merged**
